# Generated by Django 4.1.7 on 2023-04-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(blank=True, unique=True, upload_to='', verbose_name='Картинка'),
        ),
    ]
