# Generated by Django 4.1.7 on 2023-04-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_image_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(blank=True, unique=True, upload_to='media', verbose_name='Картинка'),
        ),
    ]
