# Generated by Django 4.1.7 on 2023-04-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_image_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['post']},
        ),
        migrations.AddField(
            model_name='image',
            name='my_order',
            field=models.IntegerField(default=0),
        ),
    ]
