# Generated by Django 4.2.1 on 2023-06-05 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_image_options_alter_place_description_long'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['custom_order']},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='my_order',
            new_name='custom_order',
        ),
    ]
