# Generated by Django 4.2.1 on 2023-06-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(unique=True, upload_to='media', verbose_name='Картинка'),
        ),
    ]
