# Generated by Django 4.2.1 on 2023-06-16 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_image_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='low',
            new_name='lon',
        ),
    ]
